### ISSUE TITLE
pip install error with setuptools v59+

### ISSUE THREAD

**Issue by shtoltz** [bitmazk/python-server-metrics#2]
Since version 59.0.0 setuptools not allow to use newline characters in description - https://setuptools.pypa.io/en/latest/history.html#v59-0-0

Error example:
```
shtoltz@localhost:~/work/python-server-metrics$ pip install -e .
Obtaining file:///home/shtoltz/work/python-server-metrics
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/shtoltz/work/python-server-metrics/venv/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shtoltz/work/python-server-metrics/setup.py'"'"'; __file__='"'"'/home/shtoltz/work/python-server-metrics/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-spireshk
       cwd: /home/shtoltz/work/python-server-metrics/
  Complete output (26 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-spireshk/python_server_metrics.egg-info
  writing /tmp/pip-pip-egg-info-spireshk/python_server_metrics.egg-info/PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/shtoltz/work/python-server-metrics/setup.py", line 46, in <module>
      setup(
    File "/home/shtoltz/work/python-server-metrics/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/shtoltz/work/python-server-metrics/venv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/home/shtoltz/work/python-server-metrics/venv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/home/shtoltz/work/python-server-metrics/venv/lib/python3.9/site-packages/setuptools/dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "/home/shtoltz/work/python-server-metrics/venv/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
  ----------------------------------------
WARNING: Discarding file:///home/shtoltz/work/python-server-metrics. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

After remove newline in DESCRIPTION package installed without errors:
```
shtoltz@localhost:~/work/python-server-metrics$ pip install -e .
Obtaining file:///home/shtoltz/work/python-server-metrics
  Preparing metadata (setup.py) ... done
Collecting psutil
  Using cached psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl (293 kB)
Installing collected packages: psutil, python-server-metrics
  Running setup.py develop for python-server-metrics
Successfully installed psutil-5.8.0 python-server-metrics-0.2.1
```

I made a PR #1 that fixes this error

**Comment by shtoltz** [comment]
Thanks!
